org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.109

mod_id=gobg
mod_name=Galactica Overdrive:Beyond the Gods
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.kurimeshi.gobg

geckolib_version=5.5.2
curios_version_id=15.0.0